// 自动生成：由本地 dev.db 提取的字典/系统参数初始种子数据。
// 容器首次部署（空库）时由 seed.ts 写入，保证「字典管理 / 系统参数」有初始内容。
// 如需调整初始值，请改本地 dev.db 后重新提取，不要手改此处。
/* eslint-disable */

export interface SeedDictType { code: string; name: string; remark: string | null; sort: number; status: number; isSystem: boolean; scope: string; }
export interface SeedDictItem { typeCode: string; itemCode: string; itemName: string; sortOrder: number; status: number; color: string | null; remark: string | null; extField1: string | null; }
export interface SeedSysParam { key: string; value: string | null; remark: string | null; }

export const dictTypes: SeedDictType[] = [
  { code: "yes_no", name: "是/否", remark: null, sort: 0, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "contract_type", name: "合同类型", remark: null, sort: 1, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "industry_type", name: "项目业态", remark: null, sort: 1, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "contract_execution_status", name: "合同执行情况", remark: null, sort: 2, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "contract_sub_type", name: "合同子类型", remark: null, sort: 2, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "approval_status", name: "申请状态", remark: null, sort: 3, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "material_category_l1", name: "物资一级分类", remark: "物资基础库一级分类，与字典管理共享同一份数据源", sort: 4, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "supplement_agreement_type", name: "补充协议类型", remark: null, sort: 4, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "asset_status", name: "资产状态", remark: null, sort: 5, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "contract_status", name: "合同起草状态", remark: null, sort: 5, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "material_category_l2", name: "物资二级分类", remark: "物资基础库二级分类，与字典管理共享同一份数据源", sort: 5, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "material_source", name: "来源", remark: null, sort: 6, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "self_project", name: "本项目", remark: "收领单「本项目」下拉数据源，可在字典管理中维护", sort: 6, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "material_category", name: "材料类别", remark: null, sort: 7, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "other_project", name: "其他项目", remark: "收领单「其他项目」下拉数据源，可在字典管理中维护", sort: 7, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "asset_ledger_source", name: "资产来源", remark: null, sort: 8, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "material_type", name: "物资种类（关联材料类别）", remark: "extField1 存储所属材料类别编码，实现与 material_category 联动", sort: 8, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "asset_category_l1", name: "资产类别（一级）", remark: null, sort: 9, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "measurement_unit", name: "计量单位", remark: null, sort: 9, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "asset_category_focus", name: "资产类别（重点关注）", remark: null, sort: 10, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "invoice_type", name: "发票类型", remark: null, sort: 10, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "invoice_status", name: "发票状态", remark: null, sort: 11, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "invoice_review_status", name: "发票信息审核状态", remark: null, sort: 12, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "finance_transfer_status", name: "财务移交情况", remark: null, sort: 13, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "goods_category", name: "商品类别", remark: null, sort: 14, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "settlement_type", name: "结算类型", remark: null, sort: 15, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "settlement_status", name: "结算状态", remark: null, sort: 16, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "payment_method", name: "付款方式", remark: null, sort: 17, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "payment_status", name: "付款状态", remark: null, sort: 18, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "payment_plan_status", name: "付款计划状态", remark: null, sort: 19, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "project_status", name: "项目状态", remark: null, sort: 20, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "project_member_role", name: "项目内角色", remark: null, sort: 21, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "procurement_source", name: "采购来源", remark: null, sort: 22, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "supplier_category", name: "分供方类别", remark: null, sort: 23, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "is_direct_purchase", name: "是否厂家直采", remark: null, sort: 24, status: 1, isSystem: true, scope: "GLOBAL" },
  { code: "contract_template_category", name: "合同模板分类", remark: null, sort: 25, status: 1, isSystem: true, scope: "GLOBAL" }
];

export const dictItems: SeedDictItem[] = [
  { typeCode: "approval_status", itemCode: "PENDING", itemName: "待处理", sortOrder: 0, status: 1, color: "processing", remark: null, extField1: null },
  { typeCode: "approval_status", itemCode: "APPROVED", itemName: "已通过", sortOrder: 1, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "approval_status", itemCode: "REJECTED", itemName: "已驳回", sortOrder: 2, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "STEEL_FORM", itemName: "钢模板", sortOrder: 0, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "POWER", itemName: "配电设施", sortOrder: 1, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "CABLE", itemName: "电线电缆", sortOrder: 2, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "TEMP_HOUSE", itemName: "临时用房", sortOrder: 3, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "BOOTH", itemName: "亭棚类", sortOrder: 4, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "WEIGHING", itemName: "称重类", sortOrder: 5, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "SMART_SITE", itemName: "智慧工地", sortOrder: 6, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "FENCE", itemName: "施工围挡", sortOrder: 7, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "BRIDGE_PART", itemName: "钢便桥零件", sortOrder: 8, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "ROAD_STEEL", itemName: "道路钢板", sortOrder: 9, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_focus", itemCode: "NONE", itemName: "非重点关注资产", sortOrder: 10, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "LARGE_EQUIP", itemName: "大型设备", sortOrder: 0, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "MACHINE", itemName: "机械设备", sortOrder: 1, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "OFFICE", itemName: "办公设施", sortOrder: 2, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "LIVING", itemName: "生活设施", sortOrder: 3, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "SAFETY", itemName: "安全文明施工设施", sortOrder: 4, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "TEMP_BUILD", itemName: "临建设施", sortOrder: 5, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "TOOLS", itemName: "工具用具", sortOrder: 6, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "TURNOVER", itemName: "周转料具", sortOrder: 7, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_category_l1", itemCode: "OTHER", itemName: "其他资产", sortOrder: 8, status: 1, color: null, remark: null, extField1: null },
  { typeCode: "asset_ledger_source", itemCode: "PURCHASE", itemName: "采购", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "asset_ledger_source", itemCode: "TRANSFER_IN", itemName: "调入", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "asset_ledger_source", itemCode: "TRANSFER_OUT", itemName: "调出", sortOrder: 2, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "asset_ledger_source", itemCode: "TRANSFER_IN_FEE", itemName: "调入费", sortOrder: 3, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "asset_ledger_source", itemCode: "MAINTENANCE", itemName: "维保费", sortOrder: 4, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "asset_ledger_source", itemCode: "DISPOSE_SALE", itemName: "处置（出售）", sortOrder: 5, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "asset_ledger_source", itemCode: "DISPOSE_RENT", itemName: "处置（出租）", sortOrder: 6, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "asset_status", itemCode: "IN_USE", itemName: "在用", sortOrder: 0, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "asset_status", itemCode: "IDLE", itemName: "闲置", sortOrder: 1, status: 1, color: "gold", remark: null, extField1: null },
  { typeCode: "asset_status", itemCode: "SCRAP", itemName: "报废", sortOrder: 2, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "asset_status", itemCode: "LOST", itemName: "丢失", sortOrder: 3, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "asset_status", itemCode: "DISPOSED", itemName: "处置", sortOrder: 4, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "contract_execution_status", itemCode: "DRAFT", itemName: "草稿", sortOrder: 0, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "contract_execution_status", itemCode: "UNUSED", itemName: "未使用", sortOrder: 1, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "contract_execution_status", itemCode: "EXECUTING", itemName: "执行中", sortOrder: 2, status: 1, color: "processing", remark: null, extField1: null },
  { typeCode: "contract_execution_status", itemCode: "DONE_UNSETTLED", itemName: "已完未结", sortOrder: 3, status: 1, color: "gold", remark: null, extField1: null },
  { typeCode: "contract_execution_status", itemCode: "DONE_SETTLED", itemName: "已完已结", sortOrder: 4, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "contract_status", itemCode: "DRAFT", itemName: "草稿中", sortOrder: 0, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "contract_status", itemCode: "COMPLETED", itemName: "已完成", sortOrder: 1, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "contract_sub_type", itemCode: "SINGLE", itemName: "单项", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "contract_sub_type", itemCode: "EXEC", itemName: "执行", sortOrder: 1, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "FRAMEWORK", itemName: "框架协议", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "PURCHASE", itemName: "采购合同", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "PURCHASE_EXEC", itemName: "采购执行合同", sortOrder: 2, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "LEASE", itemName: "租赁合同", sortOrder: 3, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "LEASE_EXEC", itemName: "租赁执行合同", sortOrder: 4, status: 1, color: "magenta", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "PRICE_UP", itemName: "涨价补充协议", sortOrder: 5, status: 1, color: "volcano", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "PRICE_DOWN", itemName: "降价补充协议", sortOrder: 6, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "ITEM_ADD", itemName: "增项补充协议", sortOrder: 7, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "QTY_ADD", itemName: "增量补充协议", sortOrder: 8, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "contract_template_category", itemCode: "OTHER_SUPP", itemName: "其他类补充协议", sortOrder: 9, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "contract_type", itemCode: "FRAMEWORK", itemName: "框架协议", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "contract_type", itemCode: "PURCHASE", itemName: "采购合同", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "contract_type", itemCode: "PURCHASE_EXEC", itemName: "采购执行合同", sortOrder: 2, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "contract_type", itemCode: "LEASE", itemName: "租赁合同", sortOrder: 3, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "contract_type", itemCode: "LEASE_EXEC", itemName: "租赁执行合同", sortOrder: 4, status: 1, color: "magenta", remark: null, extField1: null },
  { typeCode: "finance_transfer_status", itemCode: "NOT_TRANSFERRED", itemName: "未移交", sortOrder: 0, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "finance_transfer_status", itemCode: "TRANSFERRING", itemName: "移交中", sortOrder: 1, status: 1, color: "processing", remark: null, extField1: null },
  { typeCode: "finance_transfer_status", itemCode: "TRANSFERRED", itemName: "已移交", sortOrder: 2, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "goods_category", itemCode: "MATERIAL", itemName: "材料", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "goods_category", itemCode: "LEASE", itemName: "租赁", sortOrder: 1, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "goods_category", itemCode: "SERVICE", itemName: "服务", sortOrder: 2, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "goods_category", itemCode: "OTHER", itemName: "其他", sortOrder: 3, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "FACTORY", itemName: "厂房", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "RESIDENCE", itemName: "住宅", sortOrder: 1, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "RAIL_TRANSIT", itemName: "轨道交通", sortOrder: 2, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "MUNICIPAL", itemName: "市政", sortOrder: 3, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "BRIDGE", itemName: "桥梁", sortOrder: 4, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "RAILWAY", itemName: "铁路", sortOrder: 5, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "PIPE_GALLERY", itemName: "管廊", sortOrder: 6, status: 1, color: "gold", remark: null, extField1: null },
  { typeCode: "industry_type", itemCode: "OTHER", itemName: "其他", sortOrder: 7, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "invoice_review_status", itemCode: "PENDING", itemName: "待审核", sortOrder: 0, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "invoice_review_status", itemCode: "PASSED", itemName: "审核通过", sortOrder: 1, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "invoice_review_status", itemCode: "REJECTED", itemName: "审核不通过", sortOrder: 2, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "invoice_status", itemCode: "WAIT_VERIFY", itemName: "待查验", sortOrder: 0, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "invoice_status", itemCode: "VERIFIED", itemName: "已查验", sortOrder: 1, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "invoice_status", itemCode: "CERTIFIED", itemName: "已认证", sortOrder: 2, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "invoice_status", itemCode: "DEDUCTED", itemName: "已抵扣", sortOrder: 3, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "invoice_status", itemCode: "ABNORMAL", itemName: "异常", sortOrder: 4, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "invoice_status", itemCode: "CANCELLED", itemName: "作废", sortOrder: 5, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "invoice_status", itemCode: "RED", itemName: "红冲", sortOrder: 6, status: 1, color: "volcano", remark: null, extField1: null },
  { typeCode: "invoice_type", itemCode: "VAT_SPECIAL", itemName: "增值税专用发票", sortOrder: 0, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "invoice_type", itemCode: "VAT_NORMAL", itemName: "增值税普通发票", sortOrder: 1, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "invoice_type", itemCode: "OTHER", itemName: "其他", sortOrder: 2, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "is_direct_purchase", itemCode: "Y", itemName: "是", sortOrder: 0, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "is_direct_purchase", itemCode: "N", itemName: "否", sortOrder: 1, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "material_category", itemCode: "ENG", itemName: "工程材料", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "material_category", itemCode: "TURNOVER", itemName: "周转材料", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "material_category", itemCode: "SAFETY", itemName: "安全材料", sortOrder: 2, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "material_category", itemCode: "SUNDRY", itemName: "零星材料", sortOrder: 3, status: 1, color: "gold", remark: null, extField1: null },
  { typeCode: "material_category", itemCode: "CI", itemName: "CI类材料", sortOrder: 4, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "material_category", itemCode: "LEASE", itemName: "租赁物资", sortOrder: 5, status: 1, color: "magenta", remark: null, extField1: null },
  { typeCode: "material_category", itemCode: "FUND", itemName: "资金费用", sortOrder: 6, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "material_category_l1", itemCode: "GC", itemName: "工程材料", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "material_category_l1", itemCode: "ZZ", itemName: "周转材料", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "material_category_l1", itemCode: "AQ", itemName: "安全材料", sortOrder: 2, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "material_category_l1", itemCode: "LX", itemName: "零星材料", sortOrder: 3, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "material_category_l1", itemCode: "CI", itemName: "CI类材料", sortOrder: 4, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "material_category_l1", itemCode: "ZL", itemName: "租赁物资", sortOrder: 5, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "material_category_l1", itemCode: "ZJ", itemName: "资金费用", sortOrder: 6, status: 1, color: "gold", remark: null, extField1: null },
  { typeCode: "material_category_l2", itemCode: "GC-GJ", itemName: "钢筋", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: "工程材料" },
  { typeCode: "material_category_l2", itemCode: "GC-XG", itemName: "型钢", sortOrder: 1, status: 1, color: "blue", remark: null, extField1: "工程材料" },
  { typeCode: "material_category_l2", itemCode: "GC-DC", itemName: "地材", sortOrder: 2, status: 1, color: "blue", remark: null, extField1: "工程材料" },
  { typeCode: "material_category_l2", itemCode: "GC-ST", itemName: "商砼", sortOrder: 3, status: 1, color: "blue", remark: null, extField1: "工程材料" },
  { typeCode: "material_category_l2", itemCode: "GC-QTG", itemName: "其他钢材", sortOrder: 4, status: 1, color: "blue", remark: null, extField1: "工程材料" },
  { typeCode: "material_category_l2", itemCode: "GC-QT", itemName: "其他", sortOrder: 5, status: 1, color: "blue", remark: null, extField1: "工程材料" },
  { typeCode: "material_category_l2", itemCode: "ZZ-MB", itemName: "模板", sortOrder: 6, status: 1, color: "cyan", remark: null, extField1: "周转材料" },
  { typeCode: "material_category_l2", itemCode: "ZZ-XF", itemName: "箱房", sortOrder: 7, status: 1, color: "cyan", remark: null, extField1: "周转材料" },
  { typeCode: "material_category_l2", itemCode: "ZZ-BF", itemName: "板房", sortOrder: 8, status: 1, color: "cyan", remark: null, extField1: "周转材料" },
  { typeCode: "material_category_l2", itemCode: "ZZ-DB", itemName: "地磅", sortOrder: 9, status: 1, color: "cyan", remark: null, extField1: "周转材料" },
  { typeCode: "material_category_l2", itemCode: "ZZ-ZHGD", itemName: "智慧工地", sortOrder: 10, status: 1, color: "cyan", remark: null, extField1: "周转材料" },
  { typeCode: "material_category_l2", itemCode: "ZZ-QT", itemName: "其他", sortOrder: 11, status: 1, color: "cyan", remark: null, extField1: "周转材料" },
  { typeCode: "material_category_l2", itemCode: "AQ-PDX", itemName: "配电箱", sortOrder: 12, status: 1, color: "red", remark: null, extField1: "安全材料" },
  { typeCode: "material_category_l2", itemCode: "AQ-DLX", itemName: "电缆线", sortOrder: 13, status: 1, color: "red", remark: null, extField1: "安全材料" },
  { typeCode: "material_category_l2", itemCode: "AQ-TGCL", itemName: "土工材料", sortOrder: 14, status: 1, color: "red", remark: null, extField1: "安全材料" },
  { typeCode: "material_category_l2", itemCode: "AQ-QT", itemName: "其他", sortOrder: 15, status: 1, color: "red", remark: null, extField1: "安全材料" },
  { typeCode: "material_category_l2", itemCode: "LX-LX", itemName: "零星材料", sortOrder: 16, status: 1, color: "orange", remark: null, extField1: "零星材料" },
  { typeCode: "material_category_l2", itemCode: "CI-CI", itemName: "CI类材料", sortOrder: 17, status: 1, color: "purple", remark: null, extField1: "CI类材料" },
  { typeCode: "material_category_l2", itemCode: "ZJ-BDTX", itemName: "保底贴息", sortOrder: 18, status: 1, color: "gold", remark: null, extField1: "资金费用" },
  { typeCode: "material_category_l2", itemCode: "ZJ-YQLX", itemName: "逾期利息", sortOrder: 19, status: 1, color: "gold", remark: null, extField1: "资金费用" },
  { typeCode: "material_source", itemCode: "PURCHASE", itemName: "采购", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "LEASE", itemName: "租赁", sortOrder: 1, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "PROJ_TEAM_IN", itemName: "项目内部队伍调入", sortOrder: 2, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "BRANCH_IN", itemName: "分公司内部调入", sortOrder: 3, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "CROSS_BRANCH_IN", itemName: "跨分公司调入", sortOrder: 4, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "PROJ_TEAM_OUT", itemName: "项目内部队伍调出", sortOrder: 5, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "BRANCH_OUT", itemName: "分公司内部调出", sortOrder: 6, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "CROSS_BRANCH_OUT", itemName: "跨分公司调出", sortOrder: 7, status: 1, color: "volcano", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "RETURN", itemName: "材料退货", sortOrder: 8, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "LABOR_RETURN", itemName: "劳务退库", sortOrder: 9, status: 1, color: "magenta", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "MIX_STATION", itemName: "自拌站", sortOrder: 10, status: 1, color: "lime", remark: null, extField1: null },
  { typeCode: "material_source", itemCode: "WASTE", itemName: "闲废处理", sortOrder: 11, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "material_type", itemCode: "STEEL", itemName: "钢材", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: "ENG" },
  { typeCode: "material_type", itemCode: "CEMENT", itemName: "水泥", sortOrder: 1, status: 1, color: "blue", remark: null, extField1: "ENG" },
  { typeCode: "material_type", itemCode: "SAND", itemName: "砂石", sortOrder: 2, status: 1, color: "cyan", remark: null, extField1: "ENG" },
  { typeCode: "material_type", itemCode: "CONCRETE", itemName: "商品砼", sortOrder: 3, status: 1, color: "cyan", remark: null, extField1: "ENG" },
  { typeCode: "material_type", itemCode: "FORMWORK", itemName: "模板木方", sortOrder: 4, status: 1, color: "gold", remark: null, extField1: "TURNOVER" },
  { typeCode: "material_type", itemCode: "SCAFFOLD", itemName: "脚手架", sortOrder: 5, status: 1, color: "gold", remark: null, extField1: "TURNOVER" },
  { typeCode: "material_type", itemCode: "HELMET", itemName: "安全防护用品", sortOrder: 6, status: 1, color: "green", remark: null, extField1: "SAFETY" },
  { typeCode: "material_type", itemCode: "NET", itemName: "安全网", sortOrder: 7, status: 1, color: "green", remark: null, extField1: "SAFETY" },
  { typeCode: "material_type", itemCode: "TOOL", itemName: "小型机具", sortOrder: 8, status: 1, color: "default", remark: null, extField1: "SUNDRY" },
  { typeCode: "material_type", itemCode: "CI_ITEM", itemName: "CI标识牌", sortOrder: 9, status: 1, color: "purple", remark: null, extField1: "CI" },
  { typeCode: "material_type", itemCode: "LEASE_STEEL", itemName: "租赁钢管", sortOrder: 10, status: 1, color: "magenta", remark: null, extField1: "LEASE" },
  { typeCode: "material_type", itemCode: "LEASE_MACHINE", itemName: "租赁机械", sortOrder: 11, status: 1, color: "magenta", remark: null, extField1: "LEASE" },
  { typeCode: "material_type", itemCode: "FEE", itemName: "资金费用类", sortOrder: 12, status: 1, color: "red", remark: null, extField1: "FUND" },
  { typeCode: "measurement_unit", itemCode: "T", itemName: "吨(t)", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "measurement_unit", itemCode: "M3", itemName: "立方米(m³)", sortOrder: 1, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "measurement_unit", itemCode: "M2", itemName: "平方米(㎡)", sortOrder: 2, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "measurement_unit", itemCode: "M", itemName: "米(m)", sortOrder: 3, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "measurement_unit", itemCode: "PCS", itemName: "件", sortOrder: 4, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "measurement_unit", itemCode: "SET", itemName: "套", sortOrder: 5, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "measurement_unit", itemCode: "UNIT", itemName: "台", sortOrder: 6, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "measurement_unit", itemCode: "KG", itemName: "千克(kg)", sortOrder: 7, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "other_project", itemCode: "OTHER-001", itemName: "城东产业园项目", sortOrder: 0, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "other_project", itemCode: "OTHER-002", itemName: "南站枢纽项目", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "payment_method", itemCode: "TRANSFER", itemName: "银行转账", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "payment_method", itemCode: "ACCEPTANCE", itemName: "银行承兑", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "payment_method", itemCode: "COMMERCIAL", itemName: "商业承兑", sortOrder: 2, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "payment_method", itemCode: "FACTORING", itemName: "保理", sortOrder: 3, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "payment_method", itemCode: "CASH", itemName: "现金", sortOrder: 4, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "payment_method", itemCode: "OFFSET", itemName: "抵账", sortOrder: 5, status: 1, color: "gold", remark: null, extField1: null },
  { typeCode: "payment_plan_status", itemCode: "WAIT", itemName: "待付款", sortOrder: 0, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "payment_plan_status", itemCode: "PARTIAL", itemName: "部分付款", sortOrder: 1, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "payment_plan_status", itemCode: "PAID", itemName: "已付款", sortOrder: 2, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "payment_plan_status", itemCode: "OVERDUE", itemName: "已逾期", sortOrder: 3, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "payment_status", itemCode: "PENDING", itemName: "待付款", sortOrder: 0, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "payment_status", itemCode: "PARTIAL", itemName: "部分付款", sortOrder: 1, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "payment_status", itemCode: "PAID", itemName: "已付款", sortOrder: 2, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "payment_status", itemCode: "FAILED", itemName: "付款失败", sortOrder: 3, status: 1, color: "red", remark: null, extField1: null },
  { typeCode: "payment_status", itemCode: "REFUNDED", itemName: "已退款", sortOrder: 4, status: 1, color: "volcano", remark: null, extField1: null },
  { typeCode: "procurement_source", itemCode: "BID", itemName: "招标采购", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "procurement_source", itemCode: "INQUIRY", itemName: "询价采购", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "procurement_source", itemCode: "NEGOTIATE", itemName: "谈判采购", sortOrder: 2, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "procurement_source", itemCode: "DIRECT", itemName: "直接采购", sortOrder: 3, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "procurement_source", itemCode: "FRAMEWORK", itemName: "框架协议", sortOrder: 4, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "project_member_role", itemCode: "ADMIN", itemName: "项目管理员", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "project_member_role", itemCode: "MEMBER", itemName: "项目成员", sortOrder: 1, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "project_member_role", itemCode: "READONLY", itemName: "只读用户", sortOrder: 2, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "project_status", itemCode: "ONGOING", itemName: "进行中", sortOrder: 0, status: 1, color: "processing", remark: null, extField1: null },
  { typeCode: "project_status", itemCode: "COMPLETED", itemName: "已完工", sortOrder: 1, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "project_status", itemCode: "ARCHIVED", itemName: "已归档", sortOrder: 2, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "self_project", itemCode: "SELF-001", itemName: "滨江商务中心项目", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "settlement_status", itemCode: "DRAFT", itemName: "草稿", sortOrder: 0, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "settlement_status", itemCode: "PENDING", itemName: "待确认", sortOrder: 1, status: 1, color: "processing", remark: null, extField1: null },
  { typeCode: "settlement_status", itemCode: "CONFIRMED", itemName: "已确认", sortOrder: 2, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "settlement_status", itemCode: "INVOICED", itemName: "已开票", sortOrder: 3, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "settlement_status", itemCode: "PAID", itemName: "已付款", sortOrder: 4, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "settlement_status", itemCode: "DONE", itemName: "已完成", sortOrder: 5, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "settlement_type", itemCode: "ADVANCE", itemName: "预付款", sortOrder: 0, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "settlement_type", itemCode: "PROGRESS", itemName: "进度款", sortOrder: 1, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "settlement_type", itemCode: "FINAL", itemName: "尾款", sortOrder: 2, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "settlement_type", itemCode: "WARRANTY", itemName: "质保金", sortOrder: 3, status: 1, color: "gold", remark: null, extField1: null },
  { typeCode: "supplement_agreement_type", itemCode: "PRICE_UP", itemName: "涨价补充协议", sortOrder: 0, status: 1, color: "volcano", remark: null, extField1: null },
  { typeCode: "supplement_agreement_type", itemCode: "PRICE_DOWN", itemName: "降价补充协议", sortOrder: 1, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "supplement_agreement_type", itemCode: "ITEM_ADD", itemName: "增项补充协议", sortOrder: 2, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "supplement_agreement_type", itemCode: "QTY_ADD", itemName: "增量补充协议", sortOrder: 3, status: 1, color: "geekblue", remark: null, extField1: null },
  { typeCode: "supplement_agreement_type", itemCode: "OTHER", itemName: "其他类补充协议", sortOrder: 4, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "supplier_category", itemCode: "MATERIAL", itemName: "材料供应商", sortOrder: 0, status: 1, color: "blue", remark: null, extField1: null },
  { typeCode: "supplier_category", itemCode: "LEASE", itemName: "租赁商", sortOrder: 1, status: 1, color: "purple", remark: null, extField1: null },
  { typeCode: "supplier_category", itemCode: "LABOR", itemName: "劳务分包", sortOrder: 2, status: 1, color: "orange", remark: null, extField1: null },
  { typeCode: "supplier_category", itemCode: "PROFESSIONAL", itemName: "专业分包", sortOrder: 3, status: 1, color: "cyan", remark: null, extField1: null },
  { typeCode: "supplier_category", itemCode: "OTHER", itemName: "其他", sortOrder: 4, status: 1, color: "default", remark: null, extField1: null },
  { typeCode: "yes_no", itemCode: "Y", itemName: "是", sortOrder: 0, status: 1, color: "green", remark: null, extField1: null },
  { typeCode: "yes_no", itemCode: "N", itemName: "否", sortOrder: 1, status: 1, color: "default", remark: null, extField1: null }
];

export const sysParams: SeedSysParam[] = [
  { key: "contract.code.fixed_prefix", value: "CSCEC", remark: "合同编号固定前缀（第1段，只读）" },
  { key: "contract.code.level_mapping", value: "{\"框架协议\":\"G3\",\"采购合同\":\"G1\",\"采购执行合同\":\"G2\",\"租赁合同\":\"G1\",\"租赁执行合同\":\"G2\"}", remark: "合同类型→编号第4段合同层级（G1 采购/租赁、G2 执行类、G3 框架协议）" },
  { key: "contract.code.prefix", value: "HT", remark: "合同编号前缀" },
  { key: "contract.code.seq_digits", value: "3", remark: "合同编号顺序码位数" },
  { key: "contract.code.sub_type_mapping", value: "{\"单项\":\"G1\",\"执行\":\"G2\"}", remark: "合同子类型→编号第4段映射（JSON，按字典项名称匹配，合同层级映射缺失时回退）" },
  { key: "contract.code.type_mapping", value: "{\"框架协议\":\"WZCG\",\"采购合同\":\"WZCG\",\"采购执行合同\":\"WZCG\",\"租赁合同\":\"WZZL\",\"租赁执行合同\":\"WZZL\"}", remark: "合同类型→编号第2段映射（JSON，按字典项名称匹配）" },
  { key: "contract.code.unique.scope", value: "GLOBAL", remark: "合同编号唯一性范围：GLOBAL 全局唯一 / PROJECT 项目内唯一" },
  { key: "contract.code.year_reset", value: "true", remark: "顺序码是否按年重置" },
  { key: "contract.name.type_mapping", value: "{\"框架协议\":\"CG\",\"采购合同\":\"CG\",\"采购执行合同\":\"CG\",\"租赁合同\":\"ZL\",\"租赁执行合同\":\"ZL\"}", remark: "合同类型→合同名称第2段类型代码（CG 采购 / ZL 租赁）" },
  { key: "dict.share.scope", value: "GLOBAL", remark: "字典共享范围：GLOBAL 全局共享 / PROJECT 项目隔离" },
  { key: "finance.overdue.days360_method", value: "true", remark: "资金费用-是否使用 DAYS360 计算逾期天数" },
  { key: "finance.overdue.default_grace_days", value: "7", remark: "资金费用-默认逾期宽限天数（合同可覆盖）" },
  { key: "finance.overdue.default_monthly_rate", value: "0.006", remark: "资金费用-默认延期月利率（合同可覆盖）" },
  { key: "finance.overdue.interest_cap_ratio", value: "0.05", remark: "资金费用-逾期利息上限比例（合同可覆盖）" },
  { key: "finance.payment.mode_100_description", value: "次月25日前支付100%（逾期宽限7天）", remark: "资金费用-100%付款模式描述" },
  { key: "finance.payment.mode_3382_description", value: "第3个月内支付当月结算价款的80%，在第6个月支付第一个月的100%（逾期宽限7天）", remark: "资金费用-3382付款模式描述" },
  { key: "multi.project.enabled", value: "true", remark: "是否启用多项目" },
  { key: "repayment.code.prefix", value: "HK", remark: "还款协议编号前缀" },
  { key: "supplier.name.sync.history", value: "KEEP", remark: "供应商名称变更时历史合同处理：KEEP 保留原值 / SYNC 同步更新" },
  { key: "supplier.share.scope", value: "GLOBAL", remark: "供应商库共享范围：GLOBAL 全局共享 / PROJECT 项目隔离" }
];
